[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[dev]
  framework = "#custom"
  command = "npm run start"
  targetPort = 3000
  publish = "dist"
  autoLaunch = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
